kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: mern-shopping-app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec: 
      containers:
      - name: backend 
        image: surendraprajapati/mern-shopping-app-backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
kind: Service
apiVersion: v1
metadata:
  name: backend-service
  namespace: mern-shopping-app
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: backend-config
  namespace: mern-shopping-app
data: 
  MONGODB_URI: MONGODB_URI: "mongodb://mongo-service:27017/mern-shopping-app"