kind: Deployment 
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  namespace: mern-shopping-app
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: surendraprajapati/mern-shopping-app-frontend:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend-config

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mern-shopping-app
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: mern-shopping-app
data:
  REACT_APP_BACKEND_URL: "http://backend-service:5000"
