kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo-deployment
  namespace: mern-shopping-app
  labels:
    app: mongo
spec:
  replicas: 1
  selectors:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        
