---
- name: Configure Jenkins and SonarQube with Docker
  hosts: jenkins_sonar
  become: yes
  tasks:
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Jenkins container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - /var/jenkins_home:/var/jenkins_home

    - name: Run SonarQube container
      docker_container:
        name: sonarqube
        image: sonarqube:latest
        state: started
        restart_policy: always
        ports:
          - "9000:9000"
        env:
          SONAR_JDBC_URL: jdbc:postgresql://localhost:5432/sonar
          SONAR_JDBC_USERNAME: sonar
          SONAR_JDBC_PASSWORD: sonar

- name: Configure Artifactory with Docker
  hosts: artifactory
  become: yes
  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Artifactory OSS container
      docker_container:
        name: artifactory
        image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
        state: started
        restart_policy: always
        ports:
          - "8081:8081"


#ansible-playbook -i inventory.ini setup.yml